services:
  app:
    environment:
      WORKSPACE: ${WORKSPACE:-}
      DEVROUTER_WORKSPACE: ${DEVROUTER_WORKSPACE:-}
    volumes:
      - type: bind
        source: ${DEVROUTER_GIT_COMMON_DIR}
        target: ${DEVROUTER_GIT_COMMON_DIR}
