version: 1
devrouter:
  version: 0.0.43
project:
  name: devcontainer-demo
managedRuntime:
  devcontainer:
    baseServices: [postgres]
    profileServices: []
  processes: [app]
profiles:
  full:
    apps: ['*']
    processes: ['*']
    default: true
apps:
  - name: app
    host: devcontainer-demo.localhost
    protocol: http
    runtime: proxy
    upstream: ${WORKSPACE}-app:3000

  - name: db
    host: db.devcontainer-demo.localhost
    protocol: tcp
    tcpProtocol: postgres
    runtime: proxy
    upstream: ${WORKSPACE}-db:5432
